--Equipas
insert into Equipa values (1, 'dlasseter0', 'Gualeguaychú');
insert into Equipa values (2, 'mstrike1', 'Gaoyan');
insert into Equipa values (3, 'homara2', 'Quzi');
insert into Equipa values (4, 'fbednell3', 'Tobilolong');
insert into Equipa values (5, 'ahowler4', 'Tubuhue');
insert into Equipa values (6, 'tvennard5', 'Leran Kulon');
insert into Equipa values (7, 'tchoat6', 'Rassvet');
insert into Equipa values (8, 'jveld7', 'Nyagan');
insert into Equipa values (9, 'tteather8', 'Novovoronezh');
insert into Equipa values (10, 'dimmings9', 'Ujung Gading');
insert into Equipa values (11, 'acordeuxa', 'Tapakrejo');
insert into Equipa values (12, 'hjebbb', 'Bolboc');
insert into Equipa values (13, 'spennigarc', 'Santa Cruz');
insert into Equipa values (14, 'bpeopled', 'Uzdin');
insert into Equipa values (15, 'gbouzane', 'Caqu');
insert into Equipa values (16, 'mchottyf', 'Moravský Písek');
insert into Equipa values (17, 'cmawsong', 'Menggala');
insert into Equipa values (18, 'seschalotteh', 'San Miguel');
insert into Equipa values (19, 'plearnedi', 'Murów');
insert into Equipa values (20, 'tturrij', 'Tiberias');

--jogadores
insert into jogador values (1, 7, 'Micheil', 30, 'Extremo', 'Portugal');
insert into jogador values (2, 8, 'Gustav', 32, 'Extremo', 'Inglaterra');
insert into jogador values (3, 6, 'Mattie', 38, 'Extremo', 'Portugal');
insert into jogador values (4, 15, 'Sutherland', 32, 'Extremo', 'Inglaterra');
insert into jogador values (5, 11, 'Cale', 29, 'Extremo', 'França');
insert into jogador values (6, 1, 'Jessie', 34, 'Extremo', 'Portugal');
insert into jogador values (7, 9, 'Dennet', 37, 'Extremo', 'Portugal');
insert into jogador values (8, 7, 'Hale', 21, 'Extremo', 'Portugal');
insert into jogador values (9, 6, 'Tom', 31, 'Extremo', 'Portugal');
insert into jogador values (10, 12, 'Ebenezer', 30, 'Extremo', 'Portugal');
insert into jogador values (11, 13, 'Webster', 39, 'Extremo', 'Inglaterra');
insert into jogador values (12, 11, 'Bailey', 25, 'Extremo', 'Portugal');
insert into jogador values (13, 20, 'Shaun', 35, 'Extremo', 'Portugal');
insert into jogador values (14, 12, 'Cale', 35, 'Extremo', 'Portugal');
insert into jogador values (15, 14, 'Dell', 37, 'Extremo', 'Portugal');
insert into jogador values (16, 19, 'Simeon', 21, 'Extremo', 'Inglaterra');
insert into jogador values (17, 11, 'Monroe', 31, 'Extremo', 'França');
insert into jogador values (18, 12, 'Silvanus', 25, 'Extremo', 'Inglaterra');
insert into jogador values (19, 2, 'Vaclav', 37,'Extremo', 'Portugal');
insert into jogador values (20, 18, 'Niles', 35,'Extremo', 'Portugal');
insert into jogador values (21, 17, 'Tremaine', 32,'Defesa', 'Inglaterra');
insert into jogador values (22, 14, 'Brice', 28,'Defesa', 'Portugal');
insert into jogador values (23, 9, 'Thibaud', 25,'Defesa', 'Inglaterra');
insert into jogador values (24, 11, 'Murdoch', 29,'Defesa', 'Portugal');
insert into jogador values (25, 10, 'Rupert', 29,'Defesa', 'Portugal');
insert into jogador values (26, 10, 'Riccardo', 31,'Defesa', 'Inglaterra');
insert into jogador values (27, 4, 'Car', 32,'Defesa', 'Portugal');
insert into jogador values (28, 14, 'Brantley', 31,'Defesa', 'Inglaterra');
insert into jogador values (29, 4, 'Troy', 38,'Defesa', 'Portugal');
insert into jogador values (30, 15, 'Hewie', 27,'Defesa', 'Inglaterra');
insert into jogador values (31, 10, 'Jodie', 21,'Medio', 'Portugal');
insert into jogador values (32, 19, 'Andros', 25,'Medio', 'Inglaterra');
insert into jogador values (33, 10, 'Hirsch', 36,'Medio', 'França');
insert into jogador values (34, 18, 'Farr', 25,'Medio', 'Portugal');
insert into jogador values (35, 5, 'Spencer', 38,'Medio', 'Inglaterra');
insert into jogador values (36, 17, 'Jim', 33,'Medio', 'Portugal');
insert into jogador values (37, 8, 'Finn', 36,'Medio', 'Inglaterra');
insert into jogador values (38, 6, 'Alan', 27,'Medio', 'Portugal');
insert into jogador values (39, 16, 'Onfroi', 29,'Medio', 'Inglaterra');
insert into jogador values (40, 11, 'Cordell', 28,'Medio', 'Portugal');
insert into jogador values (41, 17, 'Edwin', 23,'Medio', 'Portugal');
insert into jogador values (42, 9, 'Lance', 37,'Medio', 'Inglaterra');
insert into jogador values (43, 13, 'Eldredge', 40,'Medio', 'Portugal');
insert into jogador values (44, 1, 'Murvyn', 38,'Medio', 'França');
insert into jogador values (45, 11, 'Findlay', 25,'Medio', 'Inglaterra');
insert into jogador values (46, 11, 'Farlay', 32,'Medio', 'Portugal');
insert into jogador values (47, 17, 'Buddie', 30,'Medio', 'Inglaterra');
insert into jogador values (48, 1, 'Reinhold', 36,'Medio', 'Portugal');
insert into jogador values (49, 3, 'Mickey', 20,'Medio', 'Portugal');
insert into jogador values (50, 18, 'Mortimer', 36,'Medio', 'Portugal');
insert into jogador values (51, 8, 'Moses', 39,'Guarda Redes', 'Inglaterra');
insert into jogador values (52, 3, 'Bartholomeo', 36,'Guarda Redes', 'Portugal');
insert into jogador values (53, 11, 'Teodorico', 29,'Guarda Redes', 'Inglaterra');
insert into jogador values (54, 9, 'Benji', 40,'Guarda Redes', 'Inglaterra');
insert into jogador values (55, 7, 'Mycah', 27,'Guarda Redes', 'Portugal');
insert into jogador values (56, 18, 'Hermon', 32,'Guarda Redes', 'França');
insert into jogador values (57, 5, 'Herculie', 27,'Guarda Redes', 'Inglaterra');
insert into jogador values (58, 15, 'Germayne', 38,'Guarda Redes', 'Portugal');
insert into jogador values (59, 12, 'Wildon', 22,'Guarda Redes', 'Portugal');
insert into jogador values (60, 5, 'Shaine', 23,'Guarda Redes', 'Inglaterra');
insert into jogador values (61, 3, 'Dionysus', 33,'Extremo', 'Portugal');
insert into jogador values (62, 16, 'Tedie', 23,'Extremo', 'Inglaterra');
insert into jogador values (63, 14, 'Lanny', 23,'Extremo', 'Inglaterra');
insert into jogador values (64, 9, 'Nappy', 39,'Extremo', 'Inglaterra');
insert into jogador values (65, 20, 'Bronnie', 36,'Extremo', 'Portugal');
insert into jogador values (66, 11, 'Reece', 20,'Extremo', 'Inglaterra');
insert into jogador values (67, 10, 'Stanislaw', 29,'Extremo', 'Portugal');
insert into jogador values (68, 17, 'Gerrard', 38,'Extremo', 'Portugal');
insert into jogador values (69, 13, 'Sam', 27,'Extremo', 'Portugal');
insert into jogador values (70, 8, 'Cassie', 29,'Extremo', 'Inglaterra');
insert into jogador values (71, 3, 'Hilarius', 20,'Extremo', 'Portugal');
insert into jogador values (72, 15, 'Morgun', 25,'Extremo', 'Portugal');
insert into jogador values (73, 15, 'Alessandro', 20,'Extremo', 'Inglaterra');
insert into jogador values (74, 7, 'Evin', 35,'Extremo', 'Inglaterra');
insert into jogador values (75, 12, 'Drake', 27,'Extremo', 'Portugal');
insert into jogador values (76, 13, 'Westbrooke', 38,'Extremo', 'Inglaterra');
insert into jogador values (77, 8, 'Rudie', 22,'Extremo', 'Portugal');
insert into jogador values (78, 18, 'Bendick', 34,'Extremo', 'Inglaterra');
insert into jogador values (79, 2, 'Filbert', 29,'Extremo', 'Portugal');
insert into jogador values (80, 14, 'Miles', 26,'Extremo', 'França');
    
--golos sofridos por guarda redes
insert into Golos_Guarda_Redes values (51, 16);
insert into Golos_Guarda_Redes values (52, 7);
insert into Golos_Guarda_Redes values (53, 10);
insert into Golos_Guarda_Redes values (54, 5);
insert into Golos_Guarda_Redes values (55, 12);
insert into Golos_Guarda_Redes values (56, 7);
insert into Golos_Guarda_Redes values (57, 8);
insert into Golos_Guarda_Redes values (58, 7);
insert into Golos_Guarda_Redes values (59, 9);
insert into Golos_Guarda_Redes values (60, 20);

--Treinadores (ID_Treinador, ID_Equipa)
insert into Treinador values (1, 1, 'Grover', 'Principal', 'Indonesia');
insert into Treinador values (2, 2, 'Gussie', 'Principal', 'China');
insert into Treinador values (3, 3, 'Carmelina', 'Principal', 'Thailand');
insert into Treinador values (4, 4, 'Karlis', 'Principal', 'Brazil');
insert into Treinador values (5, 5, 'Anson', 'Principal', 'Armenia');
insert into Treinador values (6, 6, 'Gillan', 'Principal', 'China');
insert into Treinador values (7, 7, 'Aristotle', 'Principal', 'Mali');
insert into Treinador values (8, 8, 'Alvis', 'Principal', 'Poland');
insert into Treinador values (9, 9, 'Kati', 'Principal', 'China');
insert into Treinador values (10, 10, 'Tessie', 'Principal', 'Sweden');
insert into Treinador values (11, 11, 'Nancey', 'Principal', 'United States');
insert into Treinador values (12, 12, 'Mona', 'Principal', 'China');
insert into Treinador values (13, 13, 'Ulrica', 'Principal', 'Brazil');
insert into Treinador values (14, 14, 'Clare', 'Principal', 'Finland');
insert into Treinador values (15, 15, 'Omero', 'Principal', 'Albania');
insert into Treinador values (16, 16, 'Chalmers', 'Principal', 'Peru');
insert into Treinador values (17, 17, 'Donni', 'Principal', 'Finland');
insert into Treinador values (18, 18, 'Lawry', 'Principal', 'Morocco');
insert into Treinador values (19, 19, 'Aldous', 'Principal', 'China');
insert into Treinador values (20, 20, 'Weston', 'Principal', 'Armenia');
insert into Treinador values (21, 1, 'Rosemonde', 'Adjunto', 'Vietnam');
insert into Treinador values (22, 2, 'Aaren', 'Adjunto', 'Nigeria');
insert into Treinador values (23, 3, 'Daron', 'Adjunto', 'Greece');
insert into Treinador values (24, 4, 'Sisile', 'Adjunto', 'China');
insert into Treinador values (25, 5, 'Lura', 'Adjunto', 'France');
insert into Treinador values (26, 6, 'Adelle', 'Adjunto', 'Iran');
insert into Treinador values (27, 7, 'Pam', 'Adjunto', 'China');
insert into Treinador values (28, 8, 'Simeon', 'Adjunto', 'Mexico');
insert into Treinador values (29, 9, 'Jennilee', 'Adjunto', 'Philippines');
insert into Treinador values (30, 10, 'Jasmina', 'Adjunto', 'United Kingdom');
insert into Treinador values (31, 11, 'Munroe', 'Adjunto', 'Brazil');
insert into Treinador values (32, 12, 'Holly', 'Adjunto', 'Canada');
insert into Treinador values (33, 13, 'Tally', 'Adjunto', 'Colombia');
insert into Treinador values (34, 14, 'Danyelle', 'Adjunto', 'Poland');
insert into Treinador values (35, 15, 'Robbert', 'Adjunto', 'Indonesia');
insert into Treinador values (36, 16, 'Mendy', 'Adjunto', 'Portugal');
insert into Treinador values (37, 17, 'Maura', 'Adjunto', 'Peru');
insert into Treinador values (38, 18, 'Padgett', 'Adjunto', 'Dominican Republic');
insert into Treinador values (39, 19, 'Hermie', 'Adjunto', 'China');
insert into Treinador values (40, 20, 'Prue', 'Adjunto', 'Russia');

--Ligas (ID_Liga, Divisao, Epoca, Data_Inicio, Data_Fim)
insert into Liga values (1, 1, 20132014, to_date('10/1/2013','DD/MM/YYYY'), to_date('3/7/2014','DD/MM/YYYY'));
insert into Liga values (2, 2, 20132014, to_date('20/2/2013','DD/MM/YYYY'), to_date('3/8/2014','DD/MM/YYYY'));
insert into Liga values (3, 1, 20142015, to_date('17/3/2014','DD/MM/YYYY'), to_date('21/9/2015','DD/MM/YYYY'));
insert into Liga values (4, 1, 20152016, to_date('6/4/2015','DD/MM/YYYY'), to_date('8/10/2016','DD/MM/YYYY'));
insert into Liga values (5, 1, 20162017, to_date('30/5/2016','DD/MM/YYYY'), to_date('26/11/2017','DD/MM/YYYY'));
insert into Liga values (6, 1, 20172018, to_date('1/6/2017','DD/MM/YYYY'), to_date('12/12/2018','DD/MM/YYYY'));

--Jogo (ID_Jogo, Id_Equipa_Casa, Id_Equipa_Visitante, Id_Liga, N_Golos_Casa, N_Golos_Visitante, data_)
insert into Jogo values (1, 1, 20, 1, 4, 2, to_date('5/17/2018','MM/DD/YYYY'));
insert into Jogo values (2, 2, 19, 4, 3, 4, to_date('6/2/2018','MM/DD/YYYY'));
insert into Jogo values (3, 3, 18, 5, 1, 2, to_date('4/5/2017','MM/DD/YYYY'));
insert into Jogo values (4, 4, 17, 6, 1, 4, to_date('2/11/2017','MM/DD/YYYY'));
insert into Jogo values (5, 5, 16, 2, 1, 2, to_date('11/18/2015','MM/DD/YYYY'));
insert into Jogo values (6, 6, 15, 5, 3, 4, to_date('2/1/2016','MM/DD/YYYY'));
insert into Jogo values (7, 7, 14, 4, 2, 2, to_date('8/17/2017','MM/DD/YYYY'));
insert into Jogo values (8, 8, 13, 4, 4, 3, to_date('7/29/2018','MM/DD/YYYY'));
insert into Jogo values (9, 9, 12, 6, 3, 4, to_date('4/9/2016','MM/DD/YYYY'));
insert into Jogo values (10, 10, 11, 6, 1, 1, to_date('9/18/2017','MM/DD/YYYY'));
insert into Jogo values (11, 11, 10, 3, 3, 1, to_date('3/18/2016','MM/DD/YYYY'));
insert into Jogo values (12, 12, 9, 3, 3, 3, to_date('1/15/2016','MM/DD/YYYY'));
insert into Jogo values (13, 13, 8, 5, 2, 1, to_date('9/23/2016','MM/DD/YYYY'));
insert into Jogo values (14, 14, 7, 2, 1, 3, to_date('3/26/2017','MM/DD/YYYY'));
insert into Jogo values (15, 15, 6, 1, 4, 4, to_date('3/25/2018','MM/DD/YYYY'));
insert into Jogo values (16, 16, 5, 2, 1, 3, to_date('6/29/2016','MM/DD/YYYY'));
insert into Jogo values (17, 17, 4, 6, 2, 1, to_date('1/29/2017','MM/DD/YYYY'));
insert into Jogo values (18, 18, 3, 2, 2, 1, to_date('12/4/2017','MM/DD/YYYY'));
insert into Jogo values (19, 19, 2, 1, 4, 4, to_date('4/1/2018','MM/DD/YYYY'));
insert into Jogo values (20, 20, 1, 5, 3, 4, to_date('2/8/2018','MM/DD/YYYY'));

--
